using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using FrostfallSaga.Core.Entities;
using FrostfallSaga.Core.InventorySystem;
using FrostfallSaga.Utils;

namespace FrostfallSaga.Core.HeroTeam
{
    public class HeroTeam : MonoBehaviourPersistingSingleton<HeroTeam>
    {
        private const string HERO_TEAM_CONFIGURATION_RESOURCE_PATH = "ScriptableObjects/Entities/HeroTeamConfiguration";

        /// <summary>
        ///     Automatically initialize the singleton on scene load.
        /// </summary>
        static HeroTeam()
        {
            AutoInitializeOnSceneLoad = true;
        }

        public List<Hero> Heroes { get; private set; }
        public int Stycas => _heroTeamConfiguration.Stycas;
        private HeroTeamConfigurationSO _heroTeamConfiguration;

        protected override void Init()
        {
            _heroTeamConfiguration = Resources.Load<HeroTeamConfigurationSO>(HERO_TEAM_CONFIGURATION_RESOURCE_PATH);
            if (_heroTeamConfiguration == null)
            {
                Debug.LogError("HeroTeamConfigurationSO not found at path: " + HERO_TEAM_CONFIGURATION_RESOURCE_PATH);
                return;
            }
            Heroes = new List<Hero>
            {
                new(_heroTeamConfiguration.HeroEntityConfiguration),
                new(_heroTeamConfiguration.Companion1EntityConfiguration),
                new(_heroTeamConfiguration.Companion2EntityConfiguration)
            };
            FullHealTeam(); // * For now, we fully heal the team on initialization.
        }

        /// <summary>
        /// Get the entity configurations of the alive heroes.
        /// </summary>
        /// <returns>The entity configurations of the alive heroes.</returns>
        public EntityConfigurationSO[] GetAliveHeroesEntityConfig()
        {
            return Heroes
                .Where(hero => !hero.IsDead())
                .ToList()
                .ConvertAll(hero => hero.EntityConfiguration)
                .ToArray();
        }

        /// <summary>
        /// Fully heal each hero of the team.
        /// </summary>
        public void FullHealTeam() => Heroes.ForEach(hero => hero.FullHeal());

        /// <summary>
        /// Add stycas to the team.
        /// </summary>
        /// <param name="amount">The amount of stycas to add.</param>
        public void AddStycas(int amount) => _heroTeamConfiguration.Stycas += amount;

        /// <summary>
        /// Withdraw stycas from the team. Clamped to 0.
        /// </summary>
        /// <param name="amount">The amount of stycas to withdraw. Clamped to 0.</param>
        public void WithdrawStycas(int amount) => _heroTeamConfiguration.Stycas = Math.Clamp(Stycas - amount, 0, int.MaxValue);

        /// <summary>
        /// Distribute the items to the heroes of the team.
        /// </summary>
        /// <param name="items">The items to distribute</param>
        public void DistributeItems(ItemSO[] items)
        {
            foreach (ItemSO lootedItem in items)
            {
                Inventory freeInventory = GetFirstFreeInventoryForItem(Heroes, lootedItem);
                if (freeInventory == null)
                {
                    Debug.Log("No free inventory slot found for looted item");
                    break;
                }
                freeInventory.AddItemToBag(lootedItem);
            }
        }

        /// <summary>
        /// Collect the reward that will be generated by the given reward configuration.
        /// </summary>
        /// <param name="rewardConfiguration">The reward configuration to generate the reward from.</param>
        public void CollectReward(RewardConfiguration rewardConfiguration)
        {
            AddStycas(rewardConfiguration.GenerateStycasReward());
            DistributeItems(rewardConfiguration.GenerateItemsReward());
        }

        private Inventory GetFirstFreeInventoryForItem(List<Hero> heroes, ItemSO item)
        {
            return heroes
                .Select(hero => hero.PersistedFighterConfiguration.Inventory)
                .FirstOrDefault(inventory => inventory.CanAddItemToBag(item));
        }
    }
}